apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: newapp-newapp-poi-map-app-dev
  annotations:
    argocd/app-name: newapp-newapp-poi-map-app-dev
    backstage.io/kubernetes-id: newapp-newapp-poi-map-app-dev
    backstage.io/kubernetes-namespace: newapp
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=newapp-newapp-poi-map-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23Janus2/newapp-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.summit23blues.6mbu.p1.openshiftapps.com/dev-pipelines/ns/newapp/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.summit23blues.6mbu.p1.openshiftapps.com/k8s/ns/newapp/deployments/newapp-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.summit23blues.6mbu.p1.openshiftapps.com/#https://github.com/Summit23Janus2/newapp-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://newapp-poi-map-app-newapp.apps.summit23blues.6mbu.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/carlosolivasio"
  system: workshop-system-newapp
  consumesApis:
    - gateway-api-newapp
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-newapp
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/carlosolivasio"
